{% set name = "xproj" %}
{% set version = "0.1.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0be38262d78c00ab0429839eb980b14a04e420d381fb67673f2c42d21c17feac

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >={{ python_min }}
    - xarray
    - pyproj

test:
  imports:
    - xproj
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/benbovy/xproj
  summary: Xarray extension for managing geospatial coordinate reference systems.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://xproj.readthedocs.io/
  dev_url: https://github.com/benbovy/xproj

extra:
  recipe-maintainers:
    - benbovy
    - scottyhq
