{% set name = "xproj" %}
{% set version = "0.2.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 63113443c8232e79bf04b5088e19389118405e6d4026a7c3c0df79a7a5146730

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=61
    - setuptools-scm >=7
  run:
    - python >={{ python_min }}
    - xarray
    - pyproj

test:
  imports:
    - xproj
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/xarray-contrib/xproj
  summary: Xarray extension for managing geospatial coordinate reference systems.
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://xproj.readthedocs.io/
  dev_url: https://github.com/xarray-contrib/xproj

extra:
  recipe-maintainers:
    - benbovy
    - scottyhq
    - dcherian
